export const projects = [
  {
    id: 5,
    image: "/projects/tictactoe.png",
    title: "Tic Tac Toe game",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description: "Simple Tic Tac Toe game web-application, developed in:",
    code: "https://github.com/diorm47/tic-tac-toe ",
    demo: "https://diorm47.github.io/tic-tac-toe",
  },
  {
    id: 6,
    image: "/projects/todo.png",
    title: "Todolist",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description: "Functional Todolist web-application, developed in:",
    code: "https://github.com/diorm47/todolist-app",
    demo: "https://github.com/diorm47/todolist-app",
  },
  {
    id: 7,
    image: "/projects/weather.jpg",
    title: "Weather",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description:
      "Weather web-application with connected API of weather information service, developed in:",
    code: "https://github.com/diorm47/weather-web-app-in-js ",
    demo: "https://diorm47.github.io/weather-web-app-in-js",
  },
  {
    id: 8,
    image: "/projects/mui.jpg",
    title: "OBLIVION",
    techlogogies: ["React.js", "MaterialUI"],
    description:
      "OBLIVION, simple web-site layout with modal application form, developed in:",
    code: "https://github.com/diorm47/reactjs-materialui-layout",
    demo: "https://react-simple-layout.netlify.app/",
  },
  {
    id: 9,
    image: "/projects/bookstore.png",
    title: "Bookstore",
    techlogogies: ["React.js", "MaterialUI"],
    description:
      "Bookstore web-site, with function adding items to cart, developed in:",
    code: "https://github.com/diorm47/bookstore-react-mui",
    demo: "https://bookstore-rho.vercel.app",
  },

  {
    id: 11,
    image: "/projects/social.png",
    title: "Social Network",
    techlogogies: [
      "React.js",
      "Redux",
      "React-Router-Dom",
      "Redux-Thunk",
      "Axios",
    ],
    description: "Social Network in React/Redux with many features:",
    code: "https://github.com/diorm47/social-network",
    demo: "https://social-network-oblivion.vercel.app",
  },
  {
    id: 12,
    image: "/projects/converter.png",
    title: "Currency converter",
    techlogogies: ["React.js", "Axios"],
    description: "Universal Currency converter as Google's converter currency.",
    code: "https://github.com/diorm47/test-task-converter-currency",
    demo: "https://test-task-converter-currency.vercel.app",
  },
  {
    id: 13,
    image: "/projects/crud.jpg",
    title: "CRUD app",
    techlogogies: ["React.js", "Redux"],
    description: "CRUD app in Ract/Redux with many functionalities.",
    code: "https://github.com/diorm47/crud-app",
    demo: "https://crud-app-blond.vercel.app",
  },
  {
    id: 10,
    image: "/projects/gamestore.png",
    title: "Game Store",
    techlogogies: ["React.js", "Redux-Toolkit", "React-Router-Dom"],
    description:
      "Game Store web-application with many functionalities, developed in:",
    code: "https://github.com/diorm47/game-store-reactjs-app",
    demo: "https://game-store-diorm47.vercel.app",
  },
  {
    id: 14,
    image: "/projects/blinqpay.jpg",
    title: "Blinqpay",
    techlogogies: ["React.js", "React-Router-Dom", "CSS"],
    description: "Blinqpay Payment responsive functional landing page.",
    code: "https://github.com/diorm47/blinqpay",
    demo: "https://blinqpay.vercel.app",
  },
  {
    id: 15,
    image: "/projects/safari.jpg",
    title: "Safari",
    techlogogies: [
      "React.js",
      "Redux",
      "React-hook-form",
      "React-Router-Dom",
      "CSS",
    ],
    description: "Safari online web-store application.",
    code: "https://github.com/diorm47/online-store",
    demo: "https://safari-store.vercel.app",
  },
  {
    id: 16,
    image: "/projects/resnota.jpg",
    title: "Resnota",
    techlogogies: ["React.js", "Redux", "React-Router-Dom", "CSS"],
    description: "RESNOTA online store web-site.",
    code: "https://github.com/diorm47/resnota",
    demo: "https://resnota.vercel.app",
  },
];
