export const projects = [
  {
    id: 1,
    image: "/projects/artel.png",
    title: "Artel",
    techlogogies: ["HTML5", "CSS"],
    description: "Artel official web-site's layout, developed in:",
    code: "https://github.com/diorm47/web-layout-artel",

    demo: "https://github.com/diorm47/web-layout-artel",
  },
  {
    id: 2,
    image: "/projects/aliexpress.png",
    title: "AliExpress",
    techlogogies: ["HTML5", "CSS"],
    description: "AliExpress official web-site's layout, developed in:",
    code: "https://github.com/diorm47/aliexpress-site-clone-layout",
    demo: "https://github.com/diorm47/aliexpress-site-clone-layout",
  },
  {
    id: 3,
    image: "/projects/amazon.jpg",
    title: "Amazon",
    techlogogies: ["HTML5", "CSS"],
    description: "Amazon official web-site's layout, developed in:",
    code: "https://github.com/diorm47/amazon-clone-web-layout",
    demo: "https://github.com/diorm47/amazon-clone-web-layout",
  },
  {
    id: 4,
    image: "/projects/base.png",
    title: "Base",
    techlogogies: ["HTML5", "CSS"],
    description: "Base simple web-layout, developed in:",
    code: "https://github.com/diorm47/base-web-layout-landing",

    demo: "https://github.com/diorm47/base-web-layout-landing",
  },
  {
    id: 5,
    image: "/projects/tictactoe.png",
    title: "Tic Tac Toe game",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description: "Simple Tic Tac Toe game web-application, developed in:",
    code: "https://github.com/diorm47/tic-tac-toe ",
    demo: "https://diorm47.github.io/tic-tac-toe",
  },
  {
    id: 6,
    image: "/projects/todo.png",
    title: "Todolist",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description: "Functional Todolist web-application, developed in:",
    code: "https://github.com/diorm47/todolist-app",
    demo: "https://github.com/diorm47/todolist-app",
  },
  {
    id: 7,
    image: "/projects/weather.jpg",
    title: "Weather",
    techlogogies: ["HTML5", "CSS", "JavaScript"],
    description:
      "Weather web-application with connected API of weather information service, developed in:",
    code: "https://github.com/diorm47/weather-web-app-in-js ",
    demo: "https://diorm47.github.io/weather-web-app-in-js",
  },
  {
    id: 8,
    image: "/projects/mui.jpg",
    title: "OBLIVION",
    techlogogies: ["React.js", "MaterialUI"],
    description:
      "OBLIVION, simple web-site layout with modal application form, developed in:",
    code: "https://github.com/diorm47/reactjs-materialui-layout",
    demo: "https://react-simple-layout.netlify.app/",
  },
  {
    id: 9,
    image: "/projects/bookstore.png",
    title: "Bookstore",
    techlogogies: ["React.js", "MaterialUI"],
    description:
      "Bookstore web-site, with function adding items to cart, developed in:",
    code: "https://github.com/diorm47/bookstore-react-mui",
    demo: "https://bookstore-rho.vercel.app",
  },
  {
    id: 10,
    image: "/projects/gamestore.png",
    title: "Game Store",
    techlogogies: ["React.js", "Redux-Toolkit", "React-Router-Dom"],
    description:
      "Game Store web-application with many functionalities, developed in:",
    code: "https://github.com/diorm47/game-store-reactjs-app",
    demo: "https://game-store-diorm47.vercel.app",
  },
  {
    id: 11,
    image: "/projects/social.png",
    title: "Social Network",
    techlogogies: ["React.js", "Redux", "React-Router-Dom", "Redux-Thunk"],
    description: "Social Network in React/Redux with many features:",
    code: "https://github.com/diorm47/social-network",
    demo: "https://social-network-oblivion.vercel.app",
  },
];
